version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-videos
    restart: always
    environment:
      MYSQL_DATABASE: dockerDB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql  # Ensure this matches the volume name defined below
    networks:
      - backend

  video-streaming:
    image: baraanajjarc/videostreamimage:latest
    container_name: video-streaming-container
    restart: always
    ports:
      - "8083:8083"
    networks:
      - backend

  upload-video:
    image: baraanajjarc/uploadfileimage:latest
    container_name: upload-video-container
    restart: always
    ports:
      - "8081:8081"
    networks:
      - backend

  file-system:
    image: baraanajjarc/filesystemimage:latest
    container_name: file-system-container
    restart: always
    ports:
      - "8082:8082"
    networks:
      - backend

  authentication-service:
    image: baraanajjarc/authenticationimage:latest
    container_name: authentication-container
    restart: always
    ports:
      - "8085:8085"
    networks:
      - backend

volumes:
  mysql:  # This defines the volume used by the mysql service
    driver: local

networks:
  backend:
